# FerrySync — native file sync client for Sailfish OS
#
# NOTICE:
# Application name defined in TARGET has a corresponding QML filename.
# If name defined in TARGET is changed, the corresponding QML file, desktop
# file, icon and translation filenames must be changed as well.

TARGET = harbour-ferry

CONFIG += sailfishapp_qml

SAILFISHAPP_ICONS = 86x86 108x108 128x128 172x172

CONFIG += sailfishapp_i18n
TRANSLATIONS += translations/harbour-ferry-*.ts

# App version: rpm/harbour-ferry.spec is the single source of truth, but it
# reaches qmake in two different ways. RPM builds pass Version and Release in
# on the command line (see %build in the spec) - the only way that works on
# OBS, where tar_git strips rpm/ out of the source tarball and the build
# service rewrites Release for its own bookkeeping. Builds that call qmake
# directly (Qt Creator, plain sfdk qmake) read the spec themselves.
# Either way the values end up in the generated _version.py, which is
# installed next to the other Python modules and read back by
# qml/utilities/version.py. Nothing in the Python code carries a hardcoded
# version.
SPEC_FILE = $$PWD/rpm/harbour-ferry.spec
isEmpty(APP_VERSION)|isEmpty(APP_RELEASE) {
    # Both values always come from the same source: a half-filled command line
    # falls back to the spec for both rather than mixing them.
    SPEC_LINES = $$cat($$SPEC_FILE, lines)
    SPEC_VERSION_LINE = $$find(SPEC_LINES, "^Version:")
    SPEC_RELEASE_LINE = $$find(SPEC_LINES, "^Release:")
    # The second replace drops the leading spaces of the spec column layout and
    # the CR of its CRLF line endings - only version characters survive.
    APP_VERSION = $$replace(SPEC_VERSION_LINE, "^Version:", "")
    APP_VERSION = $$replace(APP_VERSION, "[^0-9A-Za-z._+-]", "")
    APP_RELEASE = $$replace(SPEC_RELEASE_LINE, "^Release:", "")
    APP_RELEASE = $$replace(APP_RELEASE, "[^0-9A-Za-z._+-]", "")
    isEmpty(APP_VERSION): error("No APP_VERSION given on the qmake command line and no 'Version:' readable from $$SPEC_FILE")
    isEmpty(APP_RELEASE): error("No APP_RELEASE given on the qmake command line and no 'Release:' readable from $$SPEC_FILE")
    message(Ferry version read from spec: $${APP_VERSION}-$${APP_RELEASE})
} else {
    APP_VERSION = $$replace(APP_VERSION, "[^0-9A-Za-z._+-]", "")
    APP_RELEASE = $$replace(APP_RELEASE, "[^0-9A-Za-z._+-]", "")
    message(Ferry version from qmake arguments: $${APP_VERSION}-$${APP_RELEASE})
}

GENERATED_VERSION_PY = $$OUT_PWD/_version.py
VERSION_PY_CONTENT = \
    '$${LITERAL_HASH} Generated by qmake from rpm/harbour-ferry.spec - do not edit.' \
    '$${LITERAL_HASH} Read through qml/utilities/version.py.' \
    '' \
    'APP_VERSION = "$${APP_VERSION}"' \
    'APP_RELEASE = "$${APP_RELEASE}"'
!write_file($$GENERATED_VERSION_PY, VERSION_PY_CONTENT): error("Could not write $$GENERATED_VERSION_PY")

versionpy.files = $$GENERATED_VERSION_PY
versionpy.path = /usr/share/$${TARGET}/qml/utilities
INSTALLS += versionpy

# Background sync helper started by the systemd user service.
helper.files = helper
helper.path = /usr/share/$${TARGET}
INSTALLS += helper

# Bundled rclone binary: the matching build for the target
# architecture is picked automatically via QT_ARCH (armv7hl -> arm,
# aarch64 -> arm64, i486 -> i386).
equals(QT_ARCH, "arm64") {
    RCLONE_BINARY = $$PWD/rclone-binaries/rclone-aarch64
} else:equals(QT_ARCH, "arm") {
    RCLONE_BINARY = $$PWD/rclone-binaries/rclone-armv7hl
} else {
    RCLONE_BINARY = $$PWD/rclone-binaries/rclone-i486
}
message(Bundling rclone binary for QT_ARCH=$$QT_ARCH: $$RCLONE_BINARY)

rclonebin.path = /usr/share/$${TARGET}/bin
rclonebin.extra = install -D -m 755 $$RCLONE_BINARY $(INSTALL_ROOT)/usr/share/$${TARGET}/bin/rclone
INSTALLS += rclonebin

# Third-party license notices (rclone is MIT-licensed).
licenses.files = licenses
licenses.path = /usr/share/$${TARGET}
INSTALLS += licenses

# systemd user units for background sync.
systemduser.files = systemd/harbour-ferry-sync.service \
    systemd/harbour-ferry-sync.timer
systemduser.path = /usr/lib/systemd/user
INSTALLS += systemduser

DISTFILES += qml/harbour-ferry.qml \
    qml/cover/CoverPage.qml \
    qml/pages/MainPage.qml \
    qml/pages/SettingsPage.qml \
    qml/pages/AccountPage.qml \
    qml/pages/AccountTestPage.qml \
    qml/pages/DiagnosticsPage.qml \
    qml/pages/RemoteBrowserPage.qml \
    qml/pages/FileBrowserPage.qml \
    qml/pages/TextViewerPage.qml \
    qml/pages/TextEditorPage.qml \
    qml/pages/ImageViewerPage.qml \
    qml/pages/SyncPairEditorPage.qml \
    qml/pages/SyncLogPage.qml \
    qml/pages/Terminology.qml \
    qml/utilities/file_browser.py \
    qml/utilities/sync_pairs.py \
    qml/utilities/sync_engine.py \
    qml/utilities/settings_manager.py \
    qml/utilities/network.py \
    qml/utilities/notify.py \
    qml/utilities/timer_manager.py \
    qml/utilities/enc_libraries.py \
    translations/harbour-ferry-de.ts \
    translations/harbour-ferry-nb_NO.ts \
    qml/utilities/common.py \
    qml/utilities/version.py \
    qml/utilities/credential_store.py \
    qml/utilities/secrets_client.py \
    qml/utilities/backend_manager.py \
    qml/utilities/hostport.py \
    qml/utilities/ssh_hostkey.py \
    qml/utilities/config_manager.py \
    qml/utilities/remote_browser.py \
    qml/utilities/diagnostics.py \
    qml/utilities/backends/__init__.py \
    qml/utilities/backends/seafile.py \
    qml/utilities/backends/nextcloud.py \
    qml/utilities/backends/sftp.py \
    qml/utilities/backends/ftp.py \
    qml/utilities/backends/pcloud.py \
    qml/utilities/backends/webdav.py \
    helper/sync_helper.py \
    systemd/harbour-ferry-sync.service \
    systemd/harbour-ferry-sync.timer \
    rpm/harbour-ferry.changes \
    rpm/harbour-ferry.spec \
    harbour-ferry.desktop
