# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-ferry

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Native Seafile client for Sailfish OS
Version:    0.7.0
Release:    1
Group:      Qt/Qt
License:    Apache-2.0
URL:        https://openrepos.net
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-ferry.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   pyotherside-qml-plugin-python3-qt5
Requires:   python3-base
Requires:   libsailfishapp-launcher
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils
BuildRequires:  qt5-qttools-linguist

%description
Ferry is a native Seafile client for Sailfish OS using rclone as the
transfer and sync engine. Browse your libraries, upload and download
files, and keep local folders synchronized bidirectionally - manually or
on a schedule.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# rclone is installed with mode 755 by the qmake install rule (arch-specific
# binary picked automatically, see rclone-binaries/README.md).
chmod 755 %{buildroot}%{_datadir}/%{name}/helper/sync_helper.py
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%post
# >> post
# Reload user systemd so replaced unit files take effect immediately
# (otherwise the old unit definition stays loaded until next login).
systemctl-user daemon-reload || :
# << post

%postun
# >> postun
systemctl-user daemon-reload || :
# << postun

%files
%defattr(-,root,root,-)
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
/usr/lib/systemd/user/%{name}-sync.service
/usr/lib/systemd/user/%{name}-sync.timer
# >> files
# << files
